version: '3'

services:
  web:
    image: phppm/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
    tty: true
    stdin_open: true
    command: --debug=1 --static-directory=public/ --bootstrap=symfony

  composer:
    restart: 'no'
    image: composer
    volumes:
      - ./:/app
    command: install

  php:
    image: php:7.2-cli
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: php
