version: '3'

services:
  web:
    image: phppm/nginx
    container_name: phppm-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      #- ./public:/var/www/html
    tty: true
    stdin_open: true
    command: --debug=1 --static-directory=public/

  php-composer:
    restart: 'no'
    image: composer
    volumes:
      - ./:/app
    command: install
