dogsRead:
    path: /
    controller: App\Controller\DogsController::readAllAction
    methods: [ GET ]

dogRead:
    path: /{id}
    controller: App\Controller\DogsController::readAction
    methods: [ GET ]
    requirements:
        id: '\d+'

dogInfo:
    path: /more/{id}.{format}
    controller: App\Controller\DogsController::readAction
    methods: [ GET ]
    requirements:
        id: '\d+'
        format: 'json|rss|html'
