profileRead:
    path: /read
    controller: App\Controller\ProfileController::readProfile
    methods: [ GET ]
    defaults:
        oauth: false

profileUpdate:
    path: /update
    controller: App\Controller\ProfileController::updateProfile
    methods: [ GET ]
    defaults:
        oauth: true
