sub.route:
    path: /
    host: "sub.{domain}"
    controller: App\Controller\DefaultController::sub
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

index:
    path: /
    controller: App\Controller\DefaultController::index

profile:
    prefix: /profile
    resource: ./routes/profile.yml

localesExample:
    path:
        en: /about
        ua: /pro_nas
    controller: App\Controller\DefaultController::locale

api.v1.fogs:
    prefix: /api/v1/fogs
    resource: ./routes/api.v1.fogs.yml

default:
    path: /default/{state}
    controller: App\Controller\DefaultController::default
    methods: [ GET ]
    defaults:
      state: Currently stable

dir:
    prefix: /dir
    resource: ./routes/bunch_of_routes
    type: directory
